config/routes.rb
ProjectK::Application.routes.draw do

  get "users/profilelink"

  resources :products

  devise_for :users
  match 'users/:id' => 'users#profilelink', as: :user

  root :to => 'pages#index'

  get 'products' => 'Pages#products'
  get 'about' => 'Pages#about'
  get 'contact' => 'Pages#contact'
  get 'vehicleSearch' => 'Products#vehicleSearch'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :title, :VIN, :StockNumber, :Make, :Model, :ModelYear, :Trim, :BodyStyle, :Mileage, :EngineDescription, :Cylinders, :FuelType, :Transmission, :Price, :ExteriorColor, :InteriorColor, :OptionText, :Images, :VehicleLink, :NewUsed, :DateSold, :image

	has_attached_file :image, styles: { :medium => "450x450>", :thumb => "100x100"}

  validates_attachment :image, content_type: { content_type: ['image/jpeg','image/jpg', 'image/png', 'image/gif' ]}, size: { less_than: 5.megabytes } 
 
  validates :description, presence: true
  validates :title, presence: true
  validates :user_id, presence: true
 
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :image, :email, :password, :password_confirmation, :remember_me, :Username, :FirstName, :LastName, :Birthday, :ProfilePhoto, :Address, :Industry, :Phone
  has_attached_file :image, styles: { :medium => "450x450>", :thumb => "100x100"}
  validates_attachment :image, content_type: { content_type: ['image/jpeg','image/jpg', 'image/png', 'image/gif' ]}, size: { less_than: 5.megabytes } 
 
   # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_filter :authenticate_user!, except: [:index]
  # GET /products
  # GET /products.json

  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end


  def vehicleSearch
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
 def new
    @product = current_user.products.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = current_user.products.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = current_user.products.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = current_user.products.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profilelink
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
By YoloBrolo LLC, Coporation INC 2013 from One Hustler Way, Seattle, WA
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Appventory", root_path, class:"brand" %>  
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">

        <ul class="nav">
          <li><%= link_to "Vehicle Search", vehicleSearch_path %> </li>
          <li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "Contact Us", contact_path %></li>
        </ul>

        <ul class="nav pull-right">
     
          <% if user_signed_in? %>
          <li><%= link_to current_user.Username , user_path(current_user.id) %></li>
            <li><%= link_to "Inventory Management", products_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>ProjectCrabs</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<%= render 'layouts/header' %>

		<div class="container">
	    <% flash.each do |name, msg| %>
	        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	    <% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>


	</body>
</html>

app/views/pages/index.html.erb
<div class="hero-unit">
  <h1>Appventory</h1>
  <p>Fast Mobile App Inventory</p>
  <p>
  	<% unless user_signed_in? %>
    <%= link_to "Sign Up Now!", new_user_registration_path , class:"btn btn-primary btn-large" %>
    	<% end %>
    </a>
  </p>
</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product, html: { class: 'form-horizontal'}) do |f| %>
  <% if @product.errors.any? %>
    <%= f.error_notification %>
    <%= f.full_error :image_file_size, class: "alert alert-error"%>
    <%= f.full_error :image_content_type, class: "alert alert-error"%>
  <% end %>


 <div class="form-inputs">

    <%= f.input :image, label: "Upload an Image" %>
   <%= f.input :title, label: "Title"  %>
   <%= f.input :description, label: "Description" %>
   <%= f.input :VIN, label: "VIN"  %>
   <%= f.input :StockNumber, label: "Stock Number"  %>
   <%= f.input :ModelYear, label: "Model Year"  %>
   <%= f.input :Make, label: "Make" %>
   <%= f.input :Model, label: "Model" %>
   <%= f.input :Trim, label:  "Trim" %>
   <%= f.input :BodyStyle, label:  "Body Style" %>
   <%= f.input :Mileage, label: "Mileage" %>
   <%= f.input :EngineDescription, label:  "Engine Description" %>
   <%= f.input :Cylinders, label:  "Cylinders" %>
   <%= f.input :FuelType, label:  "Fuel Type" %>
   <%= f.input :Transmission, label:  "Transmission" %>
   <%= f.input :Price, label:  "Price" %>
   <%= f.input :ExteriorColor, label: "Exterior Color" %>
   <%= f.input :InteriorColor, label:  "Interior Color" %>
   <%= f.input :OptionText, label: "Option Text" %>
   <%= f.input :Images, label: "Images" %>
   <%= f.input :VehicleLink, label: "Vehicle Link" %>
   <%= f.input :NewUsed, label: "New / Used" %>
   <%= f.input :DateSold, label: "Date Sold" %>


    <%= f.button :submit,  class: "btn btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class= "row-fluid">
<h1>Inventory Management </h1>
<b><%= link_to 'Add Vehicle', new_product_path, class: "btn btn-primary pull-right "  %></b>
</div>

<table class="table table-bordered">
  <tr>
    <th></th>
    <th>Stock Number</th>
    <th>Year</th>
    <th>Make</th>
    <th>Model</th>
    <th>Transmission</th>
    <th>VIN</th>
    <th>Price</th>
    <th></th>
  </tr>
    <% @products.each do |product| %>
    <tr>
          <td><%= link_to image_tag(product.image(:thumb)), product %></td>
          <td><%= product.StockNumber %></td>
          <td><%= product.ModelYear %></td>
          <td><%= product.Make %></td>
          <td><%= product.Model %></td>
          <td><%= product.Transmission %></td>
          <td><%= product.VIN %></td>
          <td><%= product.Price %></td>

          <td><%= link_to 'View', product, class: "btn btn-primary"  %>
          <% if current_user == product.user %>
          <%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary"  %>
          <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary"  %></td>
            <% end %>
    </tr>
<% end %>
</table>

<br />

<b><%= link_to 'Add Vehicle', new_product_path, class: "btn btn-primary"  %></b>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/vehicleSearch.html.erb
<h1>View all vehicles</h1>

<table class="table table-bordered">
  <tr>
    <th></th>
    <th>Stock Number</th>
    <th>Year</th>
    <th>Make</th>
    <th>Model</th>
    <th>Transmission</th>
    <th>VIN</th>
    <th>Price</th>
    <th></th>
  </tr>
    <% @products.each do |product| %>
    <tr>
          <td><%= link_to image_tag(product.image(:thumb)), product %></td>
          <td><%= product.StockNumber %></td>
          <td><%= product.ModelYear %></td>
          <td><%= product.Make %></td>
          <td><%= product.Model %></td>
          <td><%= product.Transmission %></td>
          <td><%= product.VIN %></td>
          <td><%= product.Price %></td>

          <td><%= link_to 'View', product, class: "btn btn-primary"  %>
          <% if current_user == product.user %>
          <%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary"  %>
          <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary"  %></td>
            <% end %>
    </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/users/profilelink.html.erb
<h1><%= @user.Username %></h1>
<p><%= image_tag(@user.image(:medium)) %></p>
<p>email: <%= mail_to @user.email %></p>